- name: Aprovisionar cliente c2
  hosts: c2
  become: yes
  tasks:
    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar isc-dhcp-client
      apt:
        name: isc-dhcp-client
        state: present

    - name: Configurar interfaces de red
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto eth1
          iface eth1 inet dhcp
        owner: root
        group: root
        mode: '0644'

    - name: Reiniciar networking
      command: systemctl restart networking
      ignore_errors: yes

    - name: Solicitar IP via DHCP
      command: dhclient -v eth1
      ignore_errors: yes